[workspace]
members = [
        "rtic-apps",
        "daemon",
]
exclude = [
        "rtic-trace", # has its own workspace
        "cargo-rtic-trace", # fow now
]

[patch.crates-io]
cortex-m = { path = "/home/tmplt/exjobb/cortex-m" }