[package]
name = "rtic-trace"
version = "0.1.0"
authors = ["Viktor Sonesten <v@tmplt.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = "0.7"
rtic-trace-macros = { path = "macros", optional = true }
proc-macro2 = { version = "1", optional = true }
syn = { version = "1", optional = true, features = [ "full", "parsing" ] }
quote = { version = "1", optional = true }
include_dir = { git = "https://github.com/tmplt/include_dir.git", optional = true }
libloading = { version = "0.7", optional = true }
tempfile = { version = "3", optional = true }
rtic-syntax = { git = "https://github.com/rtic-rs/rtic-syntax.git", optional = true }
cargo = { version = "0.52", optional = true }

[dependencies.stm32f4]
version = "0.13"
features = ["stm32f401"]

[workspace]
members = [ "macros" ]

[features]
default = [ "rtic-trace-macros" ]
std = [
    "proc-macro2",
    "syn",
    "quote",
    "include_dir",
    "libloading",
    "tempfile",
    "rtic-syntax",
    "cargo",
]

[patch.crates-io]
cortex-m = { path = "../../cortex-m" }